name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - Gemfile.lock

jobs:
  sync:
    name: Sync version
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - name: Attribute commits to Dependabot
        run: |
          git config --global user.name "dependabot[bot]"
          git config --global user.email "49699333+dependabot[bot]@users.noreply.github.com"
      - name: Run version sync rake task
        run: bundle exec rake sync_version
